### ISSUE TITLE
  Create OpenAI API Key and add it to your .env file: openai

### ISSUE THREAD

**Issue by starpunjabi** [john-thuo1/chatWithPDF#1]
Could you please clarify step 4 in instructions properly. Can you create a sample .env file and add sample env names and value pairs. so openai API key can be replaced with correct value.
Currently it is not clear what would be the enviornment variable name, like openapikey, open_api_key or simply open_api etc.

**Comment by john-thuo1** [comment]
@starpunjabi Thank you for reaching out! Will update it soon.

In the meantime, in your env, specify the variable as follows :  
OPENAI_API_KEY = "Enter the Secret Key Here"

**Comment by john-thuo1** [comment]
Completed the upgrade!
